apiVersion: batch/v1
kind: CronJob
metadata:
  name: autograde
  namespace: sandbox
spec:
  schedule: '@hourly'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: autograde
              image: quay.io/ntnu/autograde:latest
              env:
                - name: HUB_URL
                  value: 'https://sandbox.apps.stack.it.ntnu.no'
                - name: HUB_USER
                  value: 'lauritko'
                - name: HUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: admin-hub-token
                      key: token
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
